---Task 36: For each state, find the total number of customers
---AND the total revenue generated by those customers.

SELECT
    c.state,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    COALESCE(
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)),
        0
    ) AS total_revenue
FROM sales.customers AS c
LEFT JOIN sales.orders AS o
    ON c.customer_id = o.customer_id
LEFT JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY c.state
ORDER BY total_revenue DESC;


---Task 37: Rank all products by price within each category.

SELECT
    p.product_name,
    p.category_id,
    p.list_price,
    RANK() OVER (
        PARTITION BY p.category_id
        ORDER BY p.list_price DESC
    ) AS price_rank
FROM production.products AS p;


---Task 38: Find the month-wise order count and total revenue for the year 2017.

SELECT
    MONTH(o.order_date) AS order_month,
    COUNT(DISTINCT o.order_id) AS order_count,
    SUM(
        oi.quantity * oi.list_price * (1 - oi.discount)
    ) AS total_revenue
FROM sales.orders AS o
INNER JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
WHERE YEAR(o.order_date) = 2017
GROUP BY MONTH(o.order_date)
ORDER BY order_month;


---Task 39: List each store's best-selling product (by quantity sold).

WITH ProductSales AS (
    SELECT
        o.store_id,
        oi.product_id,
        SUM(oi.quantity) AS total_quantity,
        RANK() OVER (
            PARTITION BY o.store_id
            ORDER BY SUM(oi.quantity) DESC
        ) AS product_rank
    FROM sales.orders AS o
    INNER JOIN sales.order_items AS oi
        ON o.order_id = oi.order_id
    GROUP BY
        o.store_id,
        oi.product_id
)
SELECT
    s.store_name,
    p.product_name,
    ps.total_quantity
FROM ProductSales AS ps
INNER JOIN sales.stores AS s
    ON ps.store_id = s.store_id
INNER JOIN production.products AS p
    ON ps.product_id = p.product_id
WHERE ps.product_rank = 1;


---Task 40: Report store name, staff name, number of orders,
---and total revenue — grouped by store and staff,
---sorted by revenue descending.

SELECT
    st.store_name,
    s.first_name + ' ' + s.last_name AS staff_name,
    COUNT(DISTINCT o.order_id) AS number_of_orders,
    COALESCE(
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)),
        0
    ) AS total_revenue
FROM sales.stores AS st
INNER JOIN sales.staffs AS s
    ON st.store_id = s.store_id
LEFT JOIN sales.orders AS o
    ON s.staff_id = o.staff_id
LEFT JOIN sales.order_items AS oi
    ON o.order_id = oi.order_id
GROUP BY
    st.store_name,
    s.first_name,
    s.last_name
ORDER BY total_revenue DESC;